on_start:
  port: 7070
  routes:
    all: /all
    playground: /play
    model: /model
    cpu: /cpu
    memory: /memory
    processes: /processes
    storages: /storages
    services: /services
    network: /network
    toggle: /toggle/{section}/{status}
on_runtime:
  # physical_memory: 1GB
  commands:
    # cpu_temp:
    #   - dash
    #   - -c
    #   - |
    #     cat /sys/class/thermal/thermal_zone*/temp \
    #     | column -s $'\t' -t \
    #     | sed 's/\(.\)..$/.\1/'
    model_name:
      - dash
      - -c
      - | 
        hostnamectl \
          | grep Operating \
          | awk -F: '{print $2}' \
          | xargs
    processes:
      - dash
      - -c
      - |
        ps -ewwo pid,user,%mem,%cpu,cmd \
          --sort=-%cpu --no-headers \
          | head -n 10 \
          | tail -n 10
    service_is_active:
      - dash
      - -c
      - systemctl is-active {service} || true
    service_is_enabled:
      - dash
      - -c
      - systemctl is-enabled {service} || true
    storage:
      - dash
      - -c
      - |
        df -B1 \
          | grep -v tmpfs \
          | grep -v none \
          | grep -v snap \
          | awk '(NR>1)' \
          | sort -k 6
  services_list:
    - monitor-api
    - monitor-web
    - smbd
    - sshd
    - syslog
