name: reusable test

on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        go-version: 
          - 1.24.5
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v4
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: |
          ~/.test_cache
          ~/go/bin
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        go mod download

    - name: Run Unit tests
      run: scripts/coverage.sh

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: $(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service=github